### PR TITLE
Sprite bounce fix

### PR DESCRIPTION
**Pull request by lewinjh**
Thanks to Krom's help and patience I've had another go at fixing the sprite bouncing (less hasty this time). @Kromster80 can you please review this when you have time? @reyandme please wait for Krom to have a look before merging.

Based on our discussion last night and reading the links you sent me, I guessed the problem is that sprites are not being rendered aligned to whole screen pixels, so sometimes due to rounding errors it samples from the wrong position.

In order to visualize this problem I added a debug boolean LINEAR_FILTER_SPRITES which filters rxTrees, rxUnits, and rxHouses atlases with GL_LINEAR. This means if sprites are not being sampled from pixel centers they will appear blurry (if sampled from center they will appear as normal). Sure enough, there's a vertical blur on most sprites with this option enabled. Since it depends on the land height, each sprite has a different amount of blur. The animation has stopped bouncing in my reproducible case as expected, but 1px lines from the neighboring atlas sprite are still visible.

AFAIK to keep sprites perfectly aligned to screen pixels two things must be true:
1. Viewport offset must be in whole pixels (glTranslatef calls)
2. Sprite position must be in whole pixels (glVertex2f calls)

After adding rounding to the relevant places, the sprites no longer look blurry with LINEAR_FILTER_SPRITES enabled (screenshot is the same in GIMP with it on/off).

The bouncing animation has also stopped bouncing in the reproducible case and there are no 1px lines around it.

### CODE REVIEW

**Comment by Kromster80** [comment]
I was happy to help with that complicated issue. 
Commit looks good to me.
One minor question - `aTexFilter` is passed around a lot. Could not we just omit that and change between linear/nearest on texture generation for all sprites? (if not, why)

**Comment by lewinjh** [comment]
Thanks!

I left aTexFilter as a parameter because I was planning to experiment with it in other areas, e.g. using linear min filter for sprites (not terrain) looks quite good for zooming out.

Also, if you set linear filtering for rxTiles it looks very bad so I wanted to avoid that (button backgrounds in GUI also look bad).

**Comment by reyandme** [comment]
Thank you both @lewinjh and @Kromster80 for your work under Remake like back in the days ;)

I think its good to have an aTexFilter option for reasons Lewin described.

**Comment by Kromster80** [comment]
@lewinjh sounds good then!

**Pull request merged**
